title_name = "Lucha Libre AAA: Heroes del Ring"
title_id = "475807D1" # GX-2001
hash = "2A412C79F6E775B1" # default.xex
#media_id = "62755835"

[[patch]]
    name = "Unlock FPS"
    desc = "Framerates higher than 60 FPS require vsync to be changed from true to false in the Xenia config."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82538198 # SmoothedFrameRate = FALSE
        value = 0x60000000
    [[patch.be8]]
        address = 0x8292bdc7 # D3DPRESENT_INTERVAL_ONE
        value = 0x01

[[patch]]
    name = "Dynamic Lighting & Shadows Shading Fix"
    desc = "Solves most dynamic lighting artifacts caused by an issue with light environments and MSAA tiling."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x822bc88c # GUseTilingCode = FALSE
        value = 0x39600000

[[patch]]
    name = "Disable Motion Blur"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82592ca8 # Motionblur = FALSE
        value = 0x39600000

[[patch]]
    name = "RTV - Flickering Decals Fix"
    desc = "Disables static decals that cause z-fighting with RTV rendering. Some visual artifacts may remain. Not necessary when using ROV."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82317f7c # StaticDecals = FALSE
        value = 0x39200000

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x822c555c
        value = 0x38a00010 # li r5, 0x10
