title_name = "TNA Impact!" # TU1
title_id = "4D5707DF" # MW-2015
hash = "4C67CACD08FD5F08" # default.xex
#media_id = "37AE817A", # Disc (USA, Europe): http://redump.org/disc/57591

[[patch]]
    name = "Dynamic Lighting & Shadows Shading Fix"
    desc = "Solves most dynamic lighting artifacts caused by an issue with light environments and MSAA tiling."
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x83355513 # GTilingMode = 0
        value = 0x00
    [[patch.be8]]
        address = 0x833553bb # GUseTilingCode = FALSE
        value = 0x00
