title_name = "Blacksite Area 51"
title_id = "4D5707D7" # MW-2007
hash = "2DB7B2CDD4107BDC" # default.xex
#media_id = "686320E3" # Disc (USA, Europe): http://redump.org/disc/12355

[[patch]]
    name = "Dynamic Lighting & Shadows Shading Fix"
    desc = "Solves most dynamic lighting artifacts caused by an issue with light environments and MSAA tiling."
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x835cd763 # GTilingMode = 0
        value = 0x00
    [[patch.be8]]
        address = 0x835cd6fb # GUseTilingCode = FALSE
        value = 0x00

[[patch]]
    name = "Disable All Post-Processing"
    author = "boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x8258b66c
        value = 0x4800
    [[patch.be16]]
        address = 0x82695714
        value = 0x4800

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x825cf7d4
        value = 0x38a00010 # li r5, 0x10
