title_name = "Magnacarta 2"
title_id = "4E4D080B" # NM-2059
hash = "B4CC5A66F752EBC3" # default.xex
#media_id = [
#    "60DA537D", # Disc 1 (USA, Europe): http://redump.org/disc/13307
#    "5DB3BBBC", # Disc 2 (USA, Europe): http://redump.org/disc/13308
#]

[[patch]]
    name = "60 FPS"
    desc = "Increases the default vsync target to 60 FPS. Disabling vsync in Xenia config for over 60 FPS is not recommended as it causes numerous timing-related gameplay issues."
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x8237bfef # D3DPRESENT_INTERVAL_ONE
        value = 0x01

[[patch]]
    name = "Dynamic Lighting & Shadows Shading Fix"
    desc = "Solves most dynamic lighting artifacts caused by an issue with light environments and MSAA tiling."
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x8321bd2b # GTilingMode = 0
        value = 0x00
    [[patch.be8]]
        address = 0x8321bcc3 # GUseTilingCode = FALSE
        value = 0x00

[[patch]]
    name = "Disable Most Post-Processing"
    author = "boma"
    is_enabled = false

    [[patch.be16]]
        address = 0x824289e0
        value = 0x4800

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8244a5d0
        value = 0x38a00010 # li r5, 0x10
