title_name = "Destroy All Humans! Path of the Furon"
title_id = "545107FE" # TQ-2046
hash = "C84FA013769BF3A4" # default.xex
#media_id = "5F172B28"

[[patch]]
    name = "Unlock FPS"
    desc = "Increases vsync target to 60 FPS and removes 30 FPS engine hard cap. Framerates higher than 60 FPS require vsync to be changed from true to false in the Xenia config, which is not recommended."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x835fc774
        value = 0x3c88889a
    [[patch.be16]]
        address = 0x82743e74
        value = 0x4800
    [[patch.be8]]
        address = 0x82e83193
        value = 0x01

[[patch]]
    name = "Disable Motion Blur"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x8276d0e0
        value = 0x39600000

[[patch]]
    name = "Disable Depth of Field"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x825fe570
        value = 0x39400000
    [[patch.be32]]
        address = 0x827e6b10
        value = 0x39600000

[[patch]]
    name = "Disable Bloom"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x827e6b04
        value = 0x39400000
    [[patch.be32]]
        address = 0x82666158
        value = 0x39600000

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be8]]
        address = 0x823bcda7
        value = 0x10
