title_name = "Saints Row" # TU1
title_id = "545107D1" # TQ-2001
#hash = "" # default.xex
#media_id = "24367742"

[[patch]]
    name = "Enable Debug Console"
    desc = "Requires keyboard_passthru to be changed from false to true in the Xenia config (Requires xenia canary version 271befc from January 25th or older)."
    author = "emoose"
    is_enabled = false

    [[patch.be32]]
        address = 0x8265f694
        value = 0x48000aa4
    [[patch.be32]]
        address = 0x82660134
        value = 0x480b8ef9
    [[patch.be32]]
        address = 0x82660268
        value = 0x480b8e14
    [[patch.be8]]
        address = 0x835f4c3e
        value = 0x01

[[patch]]
    name = "Enable r_ugly_mode"
    desc = "Higher FPS but worse graphics. Might crash when starting a game."
    author = "Hasster"
    is_enabled = false

    [[patch.be8]]
        address = 0x835f2164
        value = 0x01
    [[patch.be32]]
        address = 0x827f7a5c
        value = 0x00000000
