title_name = "The Bourne Conspiracy"
title_id = "565507D4" # VU-2004
hash = "4ED9F0381E5D4D74" # default.xex
#media_id = "36BCBAA4"

[[patch]]
    name = "60 FPS"
    desc = "Increases vsync target to 60 FPS and removes 62 FPS engine hard cap. Framerates higher than 60 FPS require vsync to be changed from true to false in the Xenia config.  Very high frame rates can potentially cause problems with QTEs and animations."
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82960358
        value = 0x60000000
    [[patch.be8]]
        address = 0x822fe247
        value = 0x01

[[patch]]
    name = "Disable Motion Blur"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82dbdabc
        value = 0x48000044

[[patch]]
    name = "Disable Depth of Field"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x82a0b3a4
        value = 0x39400000
    [[patch.be32]]
        address = 0x82a0b3b0
        value = 0x39600000

[[patch]]
    name = "16x Anisotropic Filtering"
    author = "boma"
    is_enabled = false

    [[patch.be32]]
        address = 0x827c53a4
        value = 0x38a00010
