name: Deploy to GitHub Pages

on: [push, workflow_dispatch]

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout game-patches repo
        uses: actions/checkout@v3
        with:
          repository: 'xenia-canary/game-patches'
          path: 'game-patches'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
          jekyll_src: .
